name: Build CI [Windows]

on:
  push:
    paths:
      - .github/workflows/**
      - assets/**
      - examples/**
      - include/**
      - lib/**
      - src/**
      - std/**
      - test/**
      - tools/**
      - build.py
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base=2022.06-1
            brotli=1.1.0-1
            bsdtar=3.7.7-1
            bzip2=1.0.8-4
            ca-certificates=20240203-2
            coreutils=8.32-5
            curl=8.11.1-1
            dash=0.5.12-1
            db=6.2.32-5
            gawk=5.3.1-1
            gcc-libs=13.3.0-1
            getent=2.18.90-5
            gettext=0.22.4-1
            git
            gmp=6.3.0-1
            gnupg=2.4.7-1
            gzip=1.13-1
            heimdal=7.8.0-5
            heimdal-libs=7.8.0-5
            inetutils=2.5-2
            libargp=20241207-1
            libasprintf=0.22.4-1
            libassuan=2.5.7-1
            libbz2=1.0.8-4
            libcbor=0.11.0-1
            libcurl=8.11.1-1
            libdb=6.2.32-5
            libedit=20240808_3.1-1
            libexpat=2.6.4-1
            libffi=3.4.6-1
            libfido2=1.15.0-1
            libgcrypt=1.11.0-1
            libgdbm=1.24-1
            libgettextpo=0.22.4-1
            libgnutls=3.8.8-1
            libgpg-error=1.51-1
            libhogweed=3.10.1-1
            libiconv=1.18-1
            libidn2=2.3.7-1
            libintl=0.22.4-1
            libksba=1.6.7-1
            liblz4=1.10.0-1
            liblzma=5.6.3-1
            libnettle=3.10.1-1
            libnghttp2=1.64.0-1
            libnpth=1.8-1
            libopenssl=3.4.0-1
            libp11-kit=0.25.5-2
            libpcre=8.45-4
            libpcre2_8=10.44-1
            libpsl=0.21.5-2
            libreadline=8.2.013-1
            libsqlite=3.46.1-1
            libssh2=1.11.1-1
            libtasn1=4.19.0-1
            libunistring=1.2-1
            libutil-linux=2.35.2-4
            libxcrypt=4.4.38-1
            libzstd=1.5.6-1
            mingw-w64-x86_64-adwaita-icon-theme=47.0-1
            mingw-w64-x86_64-adwaita-icon-theme-legacy=46.2-1
            mingw-w64-x86_64-atk=2.54.1-1
            mingw-w64-x86_64-atkmm=2.28.4-1
            mingw-w64-x86_64-binutils=2.43.1-1
            mingw-w64-x86_64-brotli=1.1.0-4
            mingw-w64-x86_64-bzip2=1.0.8-3
            mingw-w64-x86_64-c-ares=1.34.4-1
            mingw-w64-x86_64-ca-certificates=20241223-1
            mingw-w64-x86_64-cairo=1.18.2-2
            mingw-w64-x86_64-cairomm=1.14.5-2
            mingw-w64-x86_64-crt-git=12.0.0.r473.gce0d0bfb7-1
            mingw-w64-x86_64-curl=8.11.1-1
            mingw-w64-x86_64-dbus=1.14.10-1
            mingw-w64-x86_64-double-conversion=3.3.0-1
            mingw-w64-x86_64-egl-headers=1.5.r255.9ab6036-1
            mingw-w64-x86_64-expat=2.6.4-1
            mingw-w64-x86_64-fontconfig=2.16.0-1
            mingw-w64-x86_64-freetype=2.13.3-1
            mingw-w64-x86_64-fribidi=1.0.16-1
            mingw-w64-x86_64-gcc=14.2.0-2
            mingw-w64-x86_64-gcc-libs=14.2.0-2
            mingw-w64-x86_64-gdb=16.1-1
            mingw-w64-x86_64-gdb-multiarch=16.1-1
            mingw-w64-x86_64-gdk-pixbuf2=2.42.12-4
            mingw-w64-x86_64-gettext-libtextstyle=0.23.1-1
            mingw-w64-x86_64-gettext-runtime=0.23.1-1
            mingw-w64-x86_64-gettext-tools=0.23.1-1
            mingw-w64-x86_64-giflib=5.2.2-1
            mingw-w64-x86_64-gles-headers=3.2.r1005.d127c30-1
            mingw-w64-x86_64-glew=2.2.0-3
            mingw-w64-x86_64-glfw=3.4-1
            mingw-w64-x86_64-glib2=2.82.4-1
            mingw-w64-x86_64-glibmm=2.66.7-1
            mingw-w64-x86_64-gmp=6.3.0-2
            mingw-w64-x86_64-gnutls=3.8.8-1
            mingw-w64-x86_64-graphite2=1.3.14-3
            mingw-w64-x86_64-gtk-update-icon-cache=3.24.43-1
            mingw-w64-x86_64-gtk3=3.24.48-1
            mingw-w64-x86_64-gtkmm3=3.24.9-1
            mingw-w64-x86_64-gumbo-parser=0.12.2-1
            mingw-w64-x86_64-harfbuzz=10.2.0-2
            mingw-w64-x86_64-headers-git=12.0.0.r473.gce0d0bfb7-1
            mingw-w64-x86_64-hicolor-icon-theme=0.18-1
            mingw-w64-x86_64-hidapi=0.14.0-2
            mingw-w64-x86_64-icu=76.1-1
            mingw-w64-x86_64-isl=0.27-1
            mingw-w64-x86_64-jbigkit=2.1-5
            mingw-w64-x86_64-json-glib=1.10.6-1
            mingw-w64-x86_64-lerc=4.0.0-1
            mingw-w64-x86_64-libb2=0.98.1-2
            mingw-w64-x86_64-libdatrie=0.2.13-3
            mingw-w64-x86_64-libdeflate=1.23-1
            mingw-w64-x86_64-libepoxy=1.5.10-5
            mingw-w64-x86_64-libffi=3.4.6-1
            mingw-w64-x86_64-libiconv=1.18-1
            mingw-w64-x86_64-libidn2=2.3.7-2
            mingw-w64-x86_64-libjpeg-turbo=3.1.0-1
            mingw-w64-x86_64-libmangle-git=12.0.0.r473.gce0d0bfb7-1
            mingw-w64-x86_64-libpng=1.6.45-1
            mingw-w64-x86_64-libpsl=0.21.5-3
            mingw-w64-x86_64-librsvg=2.59.2-2
            mingw-w64-x86_64-libsigc++=2.12.1-1
            mingw-w64-x86_64-libssh2=1.11.1-1
            mingw-w64-x86_64-libsystre=1.0.1-6
            mingw-w64-x86_64-libtasn1=4.19.0-1
            mingw-w64-x86_64-libthai=0.1.29-3
            mingw-w64-x86_64-libtiff=4.7.0-1
            mingw-w64-x86_64-libtre=0.9.0-1
            mingw-w64-x86_64-libunistring=1.3-1
            mingw-w64-x86_64-libwebp=1.5.0-1
            mingw-w64-x86_64-libwinpthread-git=12.0.0.r473.gce0d0bfb7-1
            mingw-w64-x86_64-libxml2=2.12.9-2
            mingw-w64-x86_64-libzip=1.11.2-1
            mingw-w64-x86_64-litehtml=0.9-1
            mingw-w64-x86_64-lzo2=2.10-2
            mingw-w64-x86_64-make=4.4.1-3
            mingw-w64-x86_64-md4c=0.5.2-1
            mingw-w64-x86_64-mpc=1.3.1-2
            mingw-w64-x86_64-mpdecimal=4.0.0-1
            mingw-w64-x86_64-mpfr=4.2.1-2
            mingw-w64-x86_64-ncurses=6.5.20241228-3
            mingw-w64-x86_64-nettle=3.10.1-1
            mingw-w64-x86_64-nghttp2=1.64.0-1
            mingw-w64-x86_64-nghttp3=1.7.0-1
            mingw-w64-x86_64-ngtcp2=1.10.0-1
            mingw-w64-x86_64-ntldd=r19.7fb9365-4
            mingw-w64-x86_64-openssl=3.4.0-1
            mingw-w64-x86_64-p11-kit=0.25.5-1
            mingw-w64-x86_64-pango=1.56.1-1
            mingw-w64-x86_64-pangomm=2.46.4-1
            mingw-w64-x86_64-pcre2=10.44-2
            mingw-w64-x86_64-pdcurses=4.4.0-1
            mingw-w64-x86_64-pixman=0.44.2-1
            mingw-w64-x86_64-pkg-config=0.29.2-6
            mingw-w64-x86_64-python=3.12.8-2
            mingw-w64-x86_64-python-packaging=24.2-1
            mingw-w64-x86_64-python-py-cpuinfo=9.0.0-4
            mingw-w64-x86_64-qt-creator=15.0.0-2
            mingw-w64-x86_64-qt5-base=5.15.16+kde+r130-2
            mingw-w64-x86_64-qt6-5compat=6.8.1-2
            mingw-w64-x86_64-qt6-base=6.8.1-3
            mingw-w64-x86_64-qt6-declarative=6.8.1-1
            mingw-w64-x86_64-qt6-quick3d=6.8.1-1
            mingw-w64-x86_64-qt6-serialport=6.8.1-1
            mingw-w64-x86_64-qt6-shadertools=6.8.1-1
            mingw-w64-x86_64-qt6-svg=6.8.1-1
            mingw-w64-x86_64-qt6-tools=6.8.1-2
            mingw-w64-x86_64-qt6-translations=6.8.1-1
            mingw-w64-x86_64-readline=8.2.013-1
            mingw-w64-x86_64-shared-mime-info=2.4-1
            mingw-w64-x86_64-sqlite3=3.47.2-1
            mingw-w64-x86_64-tcl=8.6.13-1
            mingw-w64-x86_64-termcap=1.3.1-7
            mingw-w64-x86_64-tk=8.6.13-1
            mingw-w64-x86_64-tools-git=12.0.0.r473.gce0d0bfb7-1
            mingw-w64-x86_64-tzdata=2025a-1
            mingw-w64-x86_64-vulkan-headers=1.4.304.0-1
            mingw-w64-x86_64-vulkan-loader=1.4.304.0-1
            mingw-w64-x86_64-windows-default-manifest=6.4-4
            mingw-w64-x86_64-wineditline=2.208-1
            mingw-w64-x86_64-winpthreads-git=12.0.0.r473.gce0d0bfb7-1
            mingw-w64-x86_64-winstorecompat-git=12.0.0.r473.gce0d0bfb7-1
            mingw-w64-x86_64-xxhash=0.8.3-1
            mingw-w64-x86_64-xz=5.6.3-3
            mingw-w64-x86_64-yaml-cpp=0.8.0-1
            mingw-w64-x86_64-zlib=1.3.1-1
            mingw-w64-x86_64-zstd=1.5.6-2
            ncurses=6.5.20240831-2
            nettle=3.10.1-1
            openssh=9.9p1-1
            openssl=3.4.0-1
            xz=5.6.3-1
            zlib=1.3.1-1
            zstd=1.5.6-1

      - name: Checkout code
        run:
          git clone https://github.com/n8lang/n8

      - name: Build N8
        run: |
          cd n8
          pwd
          where g++
          python build.py
          python tools/build_exe_uninstaller.py
          python tools/build_exe_installer.py

      - name: Set Environment Path
        shell: bash
        run: |
          cd n8
          echo "N8_PATH=$PWD/dist/n8lang" >> $GITHUB_ENV

      - name: Build verification
        shell: bash
        run: |
          cd n8
          ./dist/n8lang/bin/n8
          ls -R dist

      - name: Run test scripts
        shell: cmd
        run: |
          cd n8
          .\dist\n8lang\bin\n8 .\test\arithmetic.n8
          .\dist\n8lang\bin\n8 .\test\array.n8
          .\dist\n8lang\bin\n8 .\test\digits.n8
          .\dist\n8lang\bin\n8 .\test\error_handling.n8
          .\dist\n8lang\bin\n8 .\test\flow.n8
          .\dist\n8lang\bin\n8 .\test\func.n8
          .\dist\n8lang\bin\n8 .\test\lock.n8
          .\dist\n8lang\bin\n8 .\test\loop.n8
          .\dist\n8lang\bin\n8 .\test\native.n8
          .\dist\n8lang\bin\n8 .\test\parallel.n8
          .\dist\n8lang\bin\n8 .\test\regex.n8
          .\dist\n8lang\bin\n8 .\test\test.n8 -t
          .\dist\n8lang\bin\n8 .\test\types.n8

      - name: Run examples
        shell: cmd
        run: |
          cd n8
          .\dist\n8lang\bin\n8 examples\99-beers.n8
          .\dist\n8lang\bin\n8 examples\hello.n8

      - name: Build and Test Clean Up
        run: rm -rf n8/dist/n8lang

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: n8-windows-dist
          path: n8/dist
          retention-days: 1
