name: Build CI [Windows]

on:
  push:
    paths:
      - .github/workflows/**
      - assets/**
      - examples/**
      - lib/**
      - include/**
      - src/**
      - test/**
      - build.py
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Python 3.12 Installation
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build Zhivo
        run: |
          python -m pip install requests py-cpuinfo
          python build.py

      - name: Build verification
        run: |
          dir dist
          tree dist

      - name: Run test scripts
        run: |
          dist\zhivo-win32-amd64-openmp.exe test\arithmetic.zhv
          dist\zhivo-win32-amd64-openmp.exe test\array.zhv
          dist\zhivo-win32-amd64-openmp.exe test\digits.zhv
          dist\zhivo-win32-amd64-openmp.exe test\error_handling.zhv
          dist\zhivo-win32-amd64-openmp.exe test\flow.zhv
          dist\zhivo-win32-amd64-openmp.exe test\func.zhv
          dist\zhivo-win32-amd64-openmp.exe test\loop.zhv
          dist\zhivo-win32-amd64-openmp.exe test\parallel.zhv
          dist\zhivo-win32-amd64-openmp.exe test\regex.zhv
          dist\zhivo-win32-amd64-openmp.exe test\test.zhv
          dist\zhivo-win32-amd64-openmp.exe test\types.zhv

      - name: Run examples
        run: |
          dist\zhivo-win32-amd64-openmp.exe examples\99-beers.zhv
          dist\zhivo-win32-amd64-openmp.exe examples\hello.zhv

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: zhivo-windows-dist
          path: dist/
