name: Build CI [Linux]

on:
  push:
    paths:
      - .github/workflows/**
      - assets/**
      - examples/**
      - lib/**
      - include/**
      - src/**
      - test/**
      - build.py
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Python 3.12 Installation
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Get build dependencies
        run: sudo apt install build-essential -y

      - name: Build Zhivo
        run: |
          python -m pip install requests py-cpuinfo
          python build.py

      - name: Build verification
        run: |
          ls dist -ral
          find dist | sort | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"

      - name: Run test scripts
        run: |
          start=$(date +%s%3N)
          ./dist/zhivo ./test/arithmetic.zhv
          ./dist/zhivo ./test/array.zhv
          ./dist/zhivo ./test/digits.zhv
          ./dist/zhivo ./test/error_handling.zhv
          ./dist/zhivo ./test/flow.zhv
          ./dist/zhivo ./test/func.zhv
          ./dist/zhivo ./test/loop.zhv
          ./dist/zhivo ./test/parallel.zhv
          ./dist/zhivo ./test/regex.zhv
          ./dist/zhivo ./test/test.zhv
          ./dist/zhivo ./test/types.zhv
          end=$(date +%s%3N)
          echo "Elapsed time: $((end - start)) ms"

      - name: Run examples
        run: |
          /usr/bin/time -v ./dist/zhivo ./examples/hello.zhv
          /usr/bin/time -v ./dist/zhivo ./examples/99-beers.zhv

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: zhivo-linux-dist
          path: dist/
