name: Build CI [Windows]

on:
  push:
    paths:
      - .github/workflows/**
      - assets/**
      - examples/**
      - include/**
      - lib/**
      - src/**
      - std/**
      - test/**
      - tools/**
      - build.py
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-curl-gnutls
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-glfw
            mingw-w64-x86_64-glew
            mingw-w64-x86_64-python-py-cpuinfo
            mingw-w64-x86_64-libzip
            mingw-w64-x86_64-sqlite3
            mingw-w64-x86_64-hidapi
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-gtkmm3
            mingw-w64-x86_64-gettext
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-fontconfig
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-cairomm
            mingw-w64-x86_64-pango
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-gnutls
            mingw-w64-x86_64-nettle
            mingw-w64-x86_64-ngtcp2
            git

      - name: Checkout code
        run:
          git clone https://github.com/n8lang/n8

      - name: Build N8
        run: |
          cd n8
          pwd
          where g++
          python build.py
          python tools/build_exe_uninstaller.py
          python tools/build_exe_installer.py

      - name: Set Environment Path
        shell: bash
        run: |
          cd n8
          echo "N8_PATH=$PWD/dist/n8lang" >> $GITHUB_ENV

      - name: Build verification
        shell: bash
        run: |
          cd n8
          ./dist/n8lang/bin/n8
          ls -R dist

      - name: Run test scripts
        shell: cmd
        run: |
          cd n8
          .\dist\n8lang\bin\n8 .\test\arithmetic.n8
          .\dist\n8lang\bin\n8 .\test\array.n8
          .\dist\n8lang\bin\n8 .\test\digits.n8
          .\dist\n8lang\bin\n8 .\test\error_handling.n8
          .\dist\n8lang\bin\n8 .\test\flow.n8
          .\dist\n8lang\bin\n8 .\test\func.n8
          .\dist\n8lang\bin\n8 .\test\lock.n8
          .\dist\n8lang\bin\n8 .\test\loop.n8
          .\dist\n8lang\bin\n8 .\test\native.n8
          .\dist\n8lang\bin\n8 .\test\parallel.n8
          .\dist\n8lang\bin\n8 .\test\regex.n8
          .\dist\n8lang\bin\n8 .\test\test.n8 -t
          .\dist\n8lang\bin\n8 .\test\types.n8

      - name: Run examples
        shell: cmd
        run: |
          cd n8
          .\dist\n8lang\bin\n8 examples\99-beers.n8
          .\dist\n8lang\bin\n8 examples\hello.n8

      - name: Build and Test Clean Up
        run: rm -rf n8/dist/n8lang

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: n8-windows-dist
          path: n8/dist
          retention-days: 1
