name: Build CI [Darwin]

on:
  push:
    paths:
      - .github/workflows/build_ci_darwin.yml
      - assets/**
      - examples/**
      - include/**
      - lib/**
      - src/**
      - std/**
      - test/**
      - tools/**
      - build.py
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python3 and LLVM (with OpenMP support)
        run: |
          brew reinstall --force llvm
          brew install python@3.12 libomp
          export PATH=/usr/local/opt/python@3.12/bin:$PATH

      - name: Build N8
        run: |
          export CPATH=/opt/homebrew/include
          export LIBRARY_PATH=/opt/homebrew/lib
          python -m pip install py-cpuinfo
          python build.py

      - name: Set Environment Path
        run: |
          export N8_PATH=$(pwd)/dist/n8lang

      - name: Build verification
        run: |
          ./dist/n8lang/bin/n8
          ls -ral dist
          find dist | sort | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"

      - name: Run test scripts
        run: |
          ./dist/n8lang/bin/n8 ./test/arithmetic.n8
          ./dist/n8lang/bin/n8 ./test/array.n8
          ./dist/n8lang/bin/n8 ./test/digits.n8
          ./dist/n8lang/bin/n8 ./test/error_handling.n8
          ./dist/n8lang/bin/n8 ./test/flow.n8
          ./dist/n8lang/bin/n8 ./test/func.n8
          ./dist/n8lang/bin/n8 ./test/lock.n8
          ./dist/n8lang/bin/n8 ./test/loop.n8
          ./dist/n8lang/bin/n8 ./test/native.n8
          ./dist/n8lang/bin/n8 ./test/parallel.n8
          ./dist/n8lang/bin/n8 ./test/regex.n8
          ./dist/n8lang/bin/n8 ./test/test.n8 -t
          ./dist/n8lang/bin/n8 ./test/types.n8

      - name: Run examples
        run: |
          ./dist/n8lang/bin/n8 ./examples/99-beers.n8
          ./dist/n8lang/bin/n8 ./examples/hello.n8

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: n8-darwin-dist
          path: dist/
          retention-days: 1
