name: VSCode Extension Build

on:
  push:
    paths:
      - .github/workflows/**
      - extension/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extension

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node modules
        run: |
          npm install

      - name: Build as VSCode extension
        run: |
          npx vsce package

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: n8-vsce
          path: extension/n8-lang-vsce-0.0.1.vsix
          retention-days: 1
