name: Build CI [Windows]

on:
  push:
    paths:
      - .github/workflows/**
      - assets/**
      - examples/**
      - include/**
      - src/**
      - std/**
      - test/**
      - build.py
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Python 3.12 Installation
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build N8
        run: |
          python -m pip install requests py-cpuinfo
          python build.py

      - name: Set Environment Path
        run: |
          set N8_PATH=%cd%\dist\n8lang

      - name: Build verification
        run: |
          dist\n8lang\bin\n8
          dir dist
          tree dist

      - name: Run test scripts
        run: |
          dist\n8lang\bin\n8 test\arithmetic.n8
          dist\n8lang\bin\n8 test\array.n8
          dist\n8lang\bin\n8 test\digits.n8
          dist\n8lang\bin\n8 test\error_handling.n8
          dist\n8lang\bin\n8 test\flow.n8
          dist\n8lang\bin\n8 test\func.n8
          dist\n8lang\bin\n8 test\lock.n8
          dist\n8lang\bin\n8 test\loop.n8
          dist\n8lang\bin\n8 test\native.n8
          dist\n8lang\bin\n8 test\parallel.n8
          dist\n8lang\bin\n8 test\regex.n8
          dist\n8lang\bin\n8 test\test.n8 -t
          dist\n8lang\bin\n8 test\types.n8

      - name: Run examples
        run: |
          dist\n8lang\bin\n8 examples\99-beers.n8
          dist\n8lang\bin\n8 examples\hello.n8

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: n8-windows-dist
          path: dist/
          retention-days: 1
