name: Build CI [Windows]

on:
  push:
    paths:
      - .github/workflows/**
      - assets/**
      - examples/**
      - include/**
      - src/**
      - std/**
      - test/**
      - build.py
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-glfw
            mingw-w64-x86_64-glew
            python-pip

      - name: Build N8
        run: |
          where g++
          python -m pip install --upgrade pip
          python -m pip install requests py-cpuinfo
          python build.py

      - name: Set Environment Path
        shell: bash
        run: |
          echo "N8_PATH=$PWD/dist/n8lang" >> $GITHUB_ENV

      - name: Build verification
        shell: bash
        run: |
          ./dist/n8lang/bin/n8
          ls -R dist

      - name: Run test scripts
        shell: bash
        run: |
          for test in test/*.n8; do
            if [[ "$test" != "test/test.n8" ]]; then
              ./dist/n8lang/bin/n8 "$test"
            fi
          done
          ./dist/n8lang/bin/n8 test/test.n8 -t

      - name: Run examples
        run: |
          ./dist/n8lang/bin/n8 examples/99-beers.n8
          ./dist/n8lang/bin/n8 examples/hello.n8

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: n8-windows-dist
          path: dist/
          retention-days: 1
