name: Build CI [Darwin]

on:
  push:
    paths:
      - .github/workflows/**
      - assets/**
      - examples/**
      - include/**
      - src/**
      - std/**
      - test/**
      - build.py
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull submodules
        run: |
          git submodule update --init --recursive
          git pull --recurse-submodules

      - name: Install Python3 and LLVM (with OpenMP support)
        run: |
          brew update
          brew upgrade
          brew install python@3.12 libomp
          export PATH=/usr/local/opt/python@3.12/bin:$PATH
          brew reinstall --force llvm

      - name: Build N8
        run: |
          python -m pip install requests py-cpuinfo
          python build.py

      - name: Build verification
        run: |
          ./dist/n8
          ls -ral dist
          find dist | sort | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"

      - name: Run test scripts
        run: |
          ./dist/n8 ./test/arithmetic.n8
          ./dist/n8 ./test/array.n8
          ./dist/n8 ./test/digits.n8
          ./dist/n8 ./test/error_handling.n8
          ./dist/n8 ./test/flow.n8
          ./dist/n8 ./test/func.n8
          ./dist/n8 ./test/loop.n8
          ./dist/n8 ./test/parallel.n8
          ./dist/n8 ./test/regex.n8
          ./dist/n8 ./test/test.n8
          ./dist/n8 ./test/types.n8

      - name: Run examples
        run: |
          ./dist/n8 ./examples/hello.n8
          ./dist/n8 ./examples/99-beers.n8

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: n8-darwin-dist
          path: dist/
