name: Build CI [Darwin]

on:
  push:
    paths:
      - .github/workflows/**
      - assets/**
      - examples/**
      - include/**
      - lib/**
      - src/**
      - test/**
      - build.py
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python3 and LLVM (with OpenMP support)
        run: |
          brew update
          brew upgrade
          brew install python@3.12 libomp
          export PATH=/usr/local/opt/python@3.12/bin:$PATH
          brew reinstall --force llvm

      - name: Build Zhivo
        run: |
          python build.py

      - name: Build verification
        run: |
          ls -ral dist
          find dist | sort | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"

      - name: Run test scripts
        run: |
          ./dist/zhivo-darwin-arm64-openmp ./test/arithmetic.zhv
          ./dist/zhivo-darwin-arm64-openmp ./test/array.zhv
          ./dist/zhivo-darwin-arm64-openmp ./test/digits.zhv
          ./dist/zhivo-darwin-arm64-openmp ./test/error_handling.zhv
          ./dist/zhivo-darwin-arm64-openmp ./test/flow.zhv
          ./dist/zhivo-darwin-arm64-openmp ./test/func.zhv
          ./dist/zhivo-darwin-arm64-openmp ./test/loop.zhv
          ./dist/zhivo-darwin-arm64-openmp ./test/parallel.zhv
          ./dist/zhivo-darwin-arm64-openmp ./test/regex.zhv
          ./dist/zhivo-darwin-arm64-openmp ./test/test.zhv
          ./dist/zhivo-darwin-arm64-openmp ./test/types.zhv

      - name: Run examples
        run: |
          ./dist/zhivo-darwin-arm64-openmp ./examples/hello.zhv
          ./dist/zhivo-darwin-arm64-openmp ./examples/99-beers.zhv

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: zhivo-darwin-dist
          path: dist/
