name: Build CI [Darwin]

on:
  push:
    paths:
      - .github/workflows/**
      - assets/**
      - examples/**
      - include/**
      - src/**
      - test/**
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python3 and LLVM (with OpenMP support)
        run: |
          brew update
          brew upgrade
          brew install python@3.12 libomp
          export PATH=/usr/local/opt/python@3.12/bin:$PATH
          brew reinstall --force llvm

      - name: Build Zhivo
        run: |
          python build.py

      - name: Build verification
        run: |
          ls -ral dist
          find dist | sort | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"

      - name: Run test scripts (x86)
        run: |
          ./dist/zhivo-darwin-arm64 ./test/arithmetic.zhv
          ./dist/zhivo-darwin-arm64 ./test/array.zhv
          ./dist/zhivo-darwin-arm64 ./test/digits.zhv
          ./dist/zhivo-darwin-arm64 ./test/error_handling.zhv
          ./dist/zhivo-darwin-arm64 ./test/flow.zhv
          ./dist/zhivo-darwin-arm64 ./test/func.zhv
          ./dist/zhivo-darwin-arm64 ./test/loop.zhv
          ./dist/zhivo-darwin-arm64 ./test/parallel.zhv
          ./dist/zhivo-darwin-arm64 ./test/regex.zhv
          ./dist/zhivo-darwin-arm64 ./test/test.zhv
          ./dist/zhivo-darwin-arm64 ./test/types.zhv

      - name: Run examples (x86)
        run: |
          ./dist/zhivo-darwin-arm64 ./examples/hello.zhv
          ./dist/zhivo-darwin-arm64 ./examples/99-beers.zhv
